=== icyjkk/Markup-Language-Project/xml part/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sneakers">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sneaker" maxOccurs="5" minOccurs="5">  <!--I have created the constraint of 5 occurrences-->
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="model"/>
                    <xs:element name="edition">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="height" use="required">  <!-- I have changed to required-->
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="High"/>
                                  <xs:enumeration value="Low"/>    <!-- I have created enumeration high or low -->
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="sku" use="required"/> <!-- I have changed to required-->
                </xs:complexType>
              </xs:element>
              <xs:element name="brands">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="brand" maxOccurs="unbounded" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Nike"/>
                          <xs:enumeration value="Jordan"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="type" use="optional"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="features">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="colors">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="color" type="xs:string" maxOccurs="unbounded" minOccurs="0"/> <!-- I have delete enumeration-->
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="materials">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="material" maxOccurs="6" minOccurs="6">  <!--I have created the constraint of 6 occurrences-->
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="part" use="required"> <!-- I have change to required-->
                                    <xs:simpleType>
                                      <xs:restriction base="xs:string">
                                        <xs:enumeration value="Toebox"/>
                                        <xs:enumeration value="Midsole"/>
                                        <xs:enumeration value="Outsole"/>
                                        <xs:enumeration value="Quarter"/>
                                        <xs:enumeration value="Tongue"/>
                                        <xs:enumeration value="Heel"/>    <!-- I have created enumeration of material part -->
                                      </xs:restriction>
                                    </xs:simpleType>
                                  </xs:attribute>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Date">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="day">
                            <xs:simpleType>
                              <xs:restriction base="xs:integer">
                                <xs:minInclusive value="1"/>
                                <xs:maxInclusive value="31"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="month">
                            <xs:simpleType>
                              <xs:restriction base="xs:integer">
                                <xs:minInclusive value="1"/>
                                <xs:maxInclusive value="12"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="year">
                            <xs:simpleType>
                              <xs:restriction base="xs:integer">
                                <xs:minInclusive value="1985"/>
                                <xs:maxInclusive value="9999"/>   <!-- I have created date constraint -->
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:boolean" name="limitedEdition"/>  <!-- i have change type to boolean-->
                    <xs:element name="colaboration">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="artist">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="musician" type="xs:string"/>
                                <xs:element name="designer" type="xs:string"/>  <!-- I have delete enumeration-->
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="athlete">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="sport" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="brand"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:boolean" name="deadstock"/>   <!-- i have changed type to boolean-->
                    <xs:element name="supply" type="xs:positiveInteger"/>  <!-- i have changed type to positiveInteger-->
                    <xs:element name="madein">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="country" use="required"/> <!-- i have changed use to required-->
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="PriceRetail">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:positiveInteger">  <!-- I have change base to positiveInteger-->
                            <xs:attribute  name="currency" use="required">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:enumeration value="dollar"/>
                                  <xs:enumeration value="euro"/>    <!-- I have created enumeration of currency -->
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="prices">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="price" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="size" use="required"/>
                            <xs:attribute type="xs:string" name="currency" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="img">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="src" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== icyjkk/Markup-Language-Project/xml part/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<sneakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="project.xsd">
    <sneaker id="1">
        <name sku="4280">
            <model>Jordan 1</model>
            <edition height="High">OG Chicago</edition>
        </name>
        <brands type="main">
            <brand>Nike</brand>
            <brand>Jordan</brand>
        </brands>
        <features>
            <colors>
                <color>red</color>
                <color>white</color>
                <color>black</color>
            </colors>
            <materials>
                <material part="Toebox">leather</material>
                <material part="Midsole">rubber</material>
                <material part="Outsole">rubber</material>
                <material part="Quarter">leather</material>
                <material part="Tongue">nylon</material>
                <material part="Heel">leather</material>
            </materials>
            <Date>
                <day>16</day>
                <month>09</month>
                <year>1985</year>
            </Date>
            <limitedEdition>true</limitedEdition>
            <colaboration>
                <artist>
                    <musician>no one</musician>
                    <designer>no one</designer>
                </artist>
                <athlete sport="basketball">no one</athlete>
                <brand>none</brand>
            </colaboration>
            <deadstock>true</deadstock>
            <supply>20000</supply>
            <madein country="China"/>
            <PriceRetail currency="dollar">200</PriceRetail>
        </features>
        <prices>
            <price size="40" currency="dollar">54600</price>
            <price size="42" currency="dollar">63964</price>
            <price size="42.5" currency="dollar">47600</price>
        </prices>
        <img src="https://images.stockx.com/images/Air-Jordan-1-OG-Chicago-1985-Product.jpg"/>
    </sneaker>
    <sneaker id="2">
        <name sku="DM7866-140">
            <model>Jordan 1</model>
            <edition height="Low">Fragment X Travis Scott</edition>
        </name>
        <brands type="main">
            <brand>Nike</brand>
            <brand>Jordan</brand>
        </brands>
        <features>
            <colors>
                <color>black</color>
                <color>white</color>
                <color>blue</color>
                <color>cream</color>
            </colors>
            <materials>
                <material part="Toebox">leather</material>
                <material part="Midsole">rubber</material>
                <material part="Outsole">rubber</material>
                <material part="Quarter">leather</material>
                <material part="Tongue">nylon</material>
                <material part="Heel">Synthetic leather</material>
            </materials>
            <Date>
                <day>13</day>
                <month>08</month>
                <year>2021</year>
            </Date>
            <limitedEdition>true</limitedEdition>
            <colaboration>
                <artist>
                    <musician>Traviss Scott</musician>
                    <designer>no one</designer>
                </artist>
                <athlete sport="basketball">no one</athlete>
                <brand>Fragment</brand>
            </colaboration>
            <deadstock>true</deadstock>
            <supply>70000</supply>
            <madein country="China"/>
            <PriceRetail currency="dollar">200</PriceRetail>
        </features>
        <prices>
            <price size="41" currency="dollar">2248</price>
            <price size="43" currency="dollar">2102</price>
            <price size="44" currency="dollar">2037</price>
        </prices>
        <img src="https://images.stockx.com/images/Air-Jordan-1-Low-fragment-design-x-Travis-Scott-Product.jpg"/>
    </sneaker>
    <sneaker id="3">
        <name sku="555088-311">
            <model>Jordan 1</model>
            <edition height="High">Retro Turbo Greent</edition>
        </name>
        <brands type="main">
            <brand>Nike</brand>
            <brand>Jordan</brand>
        </brands>
        <features>
            <colors>
                <color>grey</color>
                <color>white</color>
                <color>blue</color>
                <color>cream</color>
            </colors>
            <materials>
                <material part="Toebox">leather</material>
                <material part="Midsole">rubber</material>
                <material part="Outsole">rubber</material>
                <material part="Quarter">leather</material>
                <material part="Tongue">nylon</material>
                <material part="Heel">suede</material>
            </materials>
            <Date>
                <day>15</day>
                <month>02</month>
                <year>2019</year>
            </Date>
            <limitedEdition>true</limitedEdition>
            <colaboration>
                <artist>
                    <musician>no one</musician>
                    <designer>no one</designer>
                </artist>
                <athlete sport="basketball">no one</athlete>
                <brand>none</brand>
            </colaboration>
            <deadstock>true</deadstock>
            <supply>105000</supply>
            <madein country="China"/>
            <PriceRetail currency="dollar">200</PriceRetail>
        </features>
        <prices>
            <price size="40" currency="dollar">1259</price>
            <price size="42.5" currency="dollar">678</price>
            <price size="45" currency="dollar">783</price>
        </prices>
        <img src="https://images.stockx.com/images/Air-Jordan-1-Retro-High-Turbo-Green-Product.jpg"/>
    </sneaker>
    <sneaker id="4">
        <name sku="555088-140">
            <model>Jordan 1</model>
            <edition height="High">Retro Obsidian UNC</edition>
        </name>
        <brands type="main">
            <brand>Nike</brand>
            <brand>Jordan</brand>
        </brands>
        <features>
            <colors>
                <color>light blue</color>
                <color>dark blue</color>
                <color>cream</color>
            </colors>
            <materials>
                <material part="Toebox">leather</material>
                <material part="Midsole">rubber</material>
                <material part="Outsole">rubber</material>
                <material part="Quarter">leather</material>
                <material part="Tongue">nylon</material>
                <material part="Heel">synthetic leather</material>
            </materials>
            <Date>
                <day>31</day>
                <month>08</month>
                <year>2019</year>
            </Date>
            <limitedEdition>true</limitedEdition>
            <colaboration>
                <artist>
                    <musician>no one</musician>
                    <designer>no one</designer>
                </artist>
                <athlete sport="basketball">no one</athlete>
                <brand>none</brand>
            </colaboration>
            <deadstock>true</deadstock>
            <supply>100000</supply>
            <madein country="China"/>
            <PriceRetail currency="dollar">200</PriceRetail>
        </features>
        <prices>
            <price size="40" currency="dollar">801</price>
            <price size="42.5" currency="dollar">596</price>
            <price size="45" currency="dollar">631</price>
        </prices>
        <img src="https://images.stockx.com/images/Air-Jordan-1-Retro-High-UNC-Leather.jpg"/>
    </sneaker>
    <sneaker id="5">
        <name sku="AA3834-101">
            <model>Jordan 1</model>
            <edition height="High">Retro Off-White Chicago</edition>
        </name>
        <brands type="main">
            <brand>Nike</brand>
            <brand>Jordan</brand>
        </brands>
        <features>
            <colors>
                <color>white</color>
                <color>red</color>
                <color>black</color>
            </colors>
            <materials>
                <material part="Toebox">nylon</material>
                <material part="Midsole">rubber</material>
                <material part="Outsole">rubber</material>
                <material part="Quarter">nylon</material>
                <material part="Tongue">nylon</material>
                <material part="Heel">suede</material>
            </materials>
            <Date>
                <day>09</day>
                <month>1</month>
                <year>2017</year>
            </Date>
            <limitedEdition>true</limitedEdition>
            <colaboration>
                <artist>
                    <musician>no one</musician>
                    <designer>Virgil Abloh</designer>
                </artist>
                <athlete sport="basketball">no one</athlete>
                <brand>Off-White</brand>
            </colaboration>
            <deadstock>true</deadstock>
            <supply>50000</supply>
            <madein country="China"/>
            <PriceRetail currency="dollar">200</PriceRetail>
        </features>
        <prices>
            <price size="38" currency="dollar">33857</price>
            <price size="39" currency="dollar">97860</price>
            <price size="41" currency="dollar">10492</price>
            <price size="43" currency="dollar">7907$</price>
            <price size="45" currency="dollar">9060$</price>
        </prices>
        <img src="https://images.stockx.com/images/Air-Jordan-1-Retro-High-Off-White-Chicago-Product.jpg"/>
    </sneaker>
</sneakers>
